### ISSUE TITLE
Can't use managed with async

### ISSUE THREAD

**Issue by massysett** [Gabriel439/Haskell-Managed-Library#3]
Try this:

    module Foo where
    import Control.Concurrent.Async
    import Control.Monad.Managed
    import Control.Monad.Trans.Cont

    background = managed . withAsync
    background' = ContT . withAsync

`background` compiles; `background'` does not.  It seems that `Async a` is of the wrong kind.  Any suggested workarounds?  I could `newtype` the return type (something like `newtype Async' = Async' (Async ())`) but then I lose the polymorphism.  Thanks.  --Omari

**Comment by Gabriel439** [comment]
It appears that the issue is the use of point-free style.  If you convert them to a point-ful version then they both work:

```haskell
module Foo where
import Control.Concurrent.Async
import Control.Monad.Managed
import Control.Monad.Trans.Cont

background  io = managed (withAsync io)
background' io = ContT (withAsync io)
```

**Comment by massysett** [comment]
Would never have guessed that one.  Thank you very much.

**Comment by Gabriel439** [comment]
You're welcome!
