### ISSUE TITLE
`Control.Monad.Trans.Except` only available since `transformers-0.4.0.0`

### ISSUE THREAD

**Issue by sgraf812** [Gabriel439/Haskell-Managed-Library#7]
Suggestion: Either resort to some #ifdef hackiness or change the lower version bound from 0.2.0.0 to 0.4.0.0

**Comment by Gabriel439** [comment]
This is fixed in `master` (see: https://github.com/Gabriel439/Haskell-Managed-Library/blob/master/managed.cabal#L36) but I just forgot to release an updated version to Hackage.  I'll try to do that tonight.

**Comment by Gabriel439** [comment]
Alright, this is up on Hackage as `managed-1.0.4`.  I'll also blacklist `managed-1.0.3` so that the solver doesn't try to select it to solve for an older version of `transformers`
