### ISSUE TITLE
How to handle differing return types?

### ISSUE THREAD

**Issue by ivan-m** [Gabriel439/Haskell-Managed-Library#9]
Is there any way to use this library if I have a with-based function that looks like ` ... -> (a -> IO r) -> IO v` (more specifically in the case I'm considering, `v ~ (r, ExitCode)` to attach how a process terminated)?

The type of `Managed` seems to prevent it, and I'm not sure if there is a nice way to solve this (I tried to butcher this case using `ContT` and whilst the types lined up, it didn't really make it obvious that `r` was the type resulting from the callback function).

The only solution I can think of is that in this very simple case, I throw a non-successful `ExitCode` as an exception, which isn't very elegant.

**Comment by Gabriel439** [comment]
In general, for an arbitrary `r` and `v` this is not possible while still providing a `Monad` instance.  You would require an indexed monad to support the fully general case

However, if `v` is related to `r` in some way then you can still have a `Monad` instance, although I'm still not sure if the specific example you gave still supports a `Monad` instance.  Usually people do it the other way around where `r = (v, m)` where `m` is some `Monoid`

However, either way that would be outside of the scope of this library.  I'd recommend defining your own type for this specific case

**Comment by ivan-m** [comment]
Fair enough.  I ended up just throwing the `ExitCode` as an exception, which gets my types right in case others want to use them with managed.
